spring:
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:tcp://localhost/~/test
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa :
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true